
ID              = 'song_unique_id'
TITLE           = 'song_title'
ALBUM           = 'song_album'
ARTIST          = 'song_artist'
DURATION        = 'song_play_duration_sec'
YEAR            = 'song_release_year'
GENRE           = 'song_genre'
TRACK_NO        = 'song_track_no'
BITRATE         = 'song_bitrate_kbps'
SAMPLE_RATE     = 'song_sample_rate'
CHANNELS        = 'song_channels'
SIZE            = 'song_size_bytes'
LOCATION        = 'song_storage_location'
USER_RATING     = 'song_user_rating'
PLAY_COUNT      = 'song_play_count'
SONG_COUNT      = 'song_count'
